# AUTOGENERATED FROM 'queries/get_school.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class GetSchoolResult:
    id: uuid.UUID
    school_code: int
    ofcdc_code: str


async def get_school(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
) -> GetSchoolResult | None:
    return await executor.query_single(
        """\
        select Lunch::School {school_code, ofcdc_code} filter .name = <str>$name limit 1\
        """,
        name=name,
    )
