# AUTOGENERATED FROM 'queries/bank/get_bank.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetBankResult:
    id: uuid.UUID
    money: int
    owner: GetBankResultOwner


@dataclasses.dataclass
class GetBankResultOwner:
    id: uuid.UUID
    userid: int


async def get_bank(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
) -> GetBankResult | None:
    return await executor.query_single(
        """\
        select default::Bank {
          id,
          money,
          owner: {userid}
        }
        filter .name = <str>$name\
        """,
        name=name,
    )
