# AUTOGENERATED FROM 'queries/bank/get_bank_id.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class GetBankIdResult:
    id: uuid.UUID


async def get_bank_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
) -> GetBankIdResult | None:
    return await executor.query_single(
        """\
        select default::Bank filter .name = <str>$name\
        """,
        name=name,
    )
