# AUTOGENERATED FROM 'queries/bank/get_bank_by_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetBankByIdResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


async def get_bank_by_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetBankByIdResult | None:
    return await executor.query_single(
        """\
        select default::Bank { name } filter .id = <uuid>$id\
        """,
        id=id,
    )
