# AUTOGENERATED FROM 'queries/bank/is_bank_owner.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import edgedb


async def is_bank_owner(
    executor: edgedb.AsyncIOExecutor,
    *,
    ownerid: int,
    name: str,
) -> bool:
    return await executor.query_single(
        """\
        select exists (select default::Bank {id} filter .owner.userid = <int64>$ownerid and .name = <str>$name)\
        """,
        ownerid=ownerid,
        name=name,
    )
