# AUTOGENERATED FROM 'queries/bank/send_to_user.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class SendToUserResult:
    id: uuid.UUID


async def send_to_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    receiverid: int,
    sender: uuid.UUID,
    amount: int,
    fee: int,
) -> SendToUserResult | None:
    return await executor.query_single(
        """\
        with
          receiver := (select User filter .userid = <int64>$receiverid),
          sender := (select Bank filter .id = <uuid>$sender),
          data := (insert Data {amount := <int64>$amount, sender := sender.id, receiver := receiver.id}),
          def := (update sender set {transactions += data, money := .money - <int64>$amount})
        update receiver set {
          transactions += data,
          money := .money + <int64>$amount - <int64>math::ceil(<int64>$amount / 100 * <int64>$fee)
        };\
        """,
        receiverid=receiverid,
        sender=sender,
        amount=amount,
        fee=fee,
    )
