# AUTOGENERATED FROM 'queries/bank/send_to_bank.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class SendToBankResult:
    id: uuid.UUID


async def send_to_bank(
    executor: edgedb.AsyncIOExecutor,
    *,
    receiver: uuid.UUID,
    sender: uuid.UUID,
    amount: int,
    fee: int,
) -> SendToBankResult | None:
    return await executor.query_single(
        """\
        with
          receiver := (select Bank filter .id = <uuid>$receiver),
          sender := (select Bank filter .id = <uuid>$sender),
          data := (insert Data {amount := <int64>$amount, sender := sender.id, receiver := receiver.id}),
          def := (update sender set {transactions += data, money := .money - <int64>$amount}),
        update receiver set {
          transactions += data,
          money := .money + <int64>$amount - <int64>math::ceil(<int64>$amount / 100 * <int64>$fee)
        };\
        """,
        receiver=receiver,
        sender=sender,
        amount=amount,
        fee=fee,
    )
