# AUTOGENERATED FROM 'queries/bank/withdraw.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class WithdrawResult:
    id: uuid.UUID


async def withdraw(
    executor: edgedb.AsyncIOExecutor,
    *,
    receiverid: int,
    sender: uuid.UUID,
    amount: int,
    fee: int,
) -> list[WithdrawResult]:
    return await executor.query(
        """\
        with
          receiver := (select User filter .userid = <int64>$receiverid),
          sender := (select Bank filter .id = <uuid>$sender),
          data := (insert Data {amount := <int64>$amount, sender := sender.id, receiver := receiver.id}),
          def := (update sender set {transactions += data, money := .money - <int64>$amount}),
          def2 := (update receiver set {
            transactions += data,
            money := .money + <int64>$amount - <int64>math::ceil(<int64>$amount / 100 * <int64>$fee)
          }),
          def3 := (
            update receiver.banks filter .receiver = <uuid>$sender
            set {amount := .amount - <int64>$amount}
          ),
          def4 := (delete receiver.banks filter .amount = 0)
        select {def, def2, def3, def4};\
        """,
        receiverid=receiverid,
        sender=sender,
        amount=amount,
        fee=fee,
    )
