[project]
name = "finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.10.1",
    "datasets>=4.0.0",
    "gputil>=1.4.0",
    "httpx>=0.28.1",
    "marimo>=0.15.3",
    "polars>=1.33.1",
    "psutil>=7.0.0",
    "python-dotenv>=1.1.1",
    "safetensors>=0.6.2",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "transformers>=4.56.1",
]
