[project]
name = "utils"
version = "0.1.0"
description = "Utils for me"
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
  "fake-useragent==2.1.0",
  "gradio-client==1.8.0",
  "httpx==0.28.1",
  "inquirer==3.4.0",
  "tomli==2.2.1",
  "tomli-w==1.2.0",
  "tqdm==4.67.1",
  "pygithub==2.6.1"
]
