[project]
name = "utils"
version = "0.1.0"
description = "Utils for me"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
  "fake-useragent==2.2.0",
  "httpx==0.28.1",
  "inquirer==3.4.1",
  "tqdm==4.67.1",
  "pygithub==2.8.1",
  "minio==7.2.18",
  "tomli==2.3.0",
]
