[project]
name = "utils"
version = "0.1.0"
description = "Utils for me"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "tomli==2.0.1",
  "tomli-w==1.0.0",
  "inquirer==3.4.0",
  "httpx==0.27.2",
  "fake-useragent==1.5.1",
  "tqdm==4.66.5",
  "gradio-client==1.3.0",
]
requires-python = "==3.12.4"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "ruff==0.6.2",
  "python-lsp-server==1.12.0",
]
