[project]
name = "utils"
version = "0.1.0"
description = "Utils for me"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "tomli==2.0.1",
  "requests==2.31.0",
  "tomli-w==1.0.0",
  "inquirer==3.2.4",
]
requires-python = "==3.12.3"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false
