[project]
name = "utils"
version = "0.1.0"
description = "Utils for me"
readme = "README.md"
requires-python = "==3.13.3"
dependencies = [
  "fake-useragent==2.2.0",
  "httpx==0.28.1",
  "inquirer==3.4.0",
  "tqdm==4.67.1",
  "pygithub==2.6.1",
  "minio==7.2.15",
  "tomli==2.2.1",
]
