[project]
name = "utils"
version = "0.1.0"
description = "Utils for me"
readme = "README.md"
requires-python = "==3.13.0"
dependencies = [
  "fake-useragent==1.5.1",
  "gradio-client==1.4.2",
  "httpx==0.27.2",
  "inquirer==3.4.0",
  "tomli==2.0.2",
  "tomli-w==1.1.0",
  "tqdm==4.66.6"
]
