[project]
name = "isla"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.1.1",
    "safetensors>=0.6.2",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "trackio>=0.4.1",
    "transformers>=4.56.2",
]
