[project]
name = "noa"
version = "0.1.0"
description = "Backend of noa"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "fastapi==0.110.2",
  "slowapi==0.1.9",
  "httpx==0.27.0",
  "edgedb==1.9.0",
  "uvicorn==0.29.0",
  "python-multipart==0.0.9",
]
requires-python = "==3.12.3"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "python-lsp-server==1.11.0",
]
