[project]
name = "noa"
version = "0.1.0"
description = "Backend of noa"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "fastapi==0.114.2",
  "httpx==0.27.2",
  "edgedb==2.0.1",
  "uvicorn==0.30.6",
  "python-multipart==0.0.9",
]
requires-python = "==3.12.5"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "ruff-lsp==0.0.56",
  "python-lsp-server==1.12.0",
]
