[tool.poetry]
name = "sntapi"
version = "0.1.0"
description = ""
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.6"
fastapi = "0.103.2"
uvicorn = "0.23.2"
pymongo = "4.5.0"
python-dotenv = "1.0.0"
selenium = "4.13.0"
pydantic = "2.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
