[tool.poetry]
name = "sntapi"
version = "0.1.0"
description = ""
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"
fastapi = "0.100.0"
uvicorn = "0.23.0"
pymongo = "4.4.1"
python-dotenv = "1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
