[project]
name = "sas"
version = "0.1.0"
description = "The small experimental"
authors = [
  {name = "misilelab", email = "misile@duck.com"},
]
dependencies = [
  "django==5.1.2"
]
requires-python = "==3.13.0"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false
