[tool.poetry]
name = "mrl"
version = "0.1.0"
description = "Misile's Reversing Library"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.2"
z3-solver = "4.12.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
