name = "Railway"
author = "Misile"
version = "0.0.1-rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68ecff4b8e19d182816368ee422b91d0d19595c4e5e1e72b3b51020eda812ea8"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
