set positional-arguments := true
alias b := build
alias br := build-release

@build build:
  clang $1.c -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed -o $1

@build-release build-release:
  clang $1.c -O2 -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed -o $1

@program update-poetry:
  poetry self update

@program-lock update-poetry-lock:
  poetry lock

@program-dep update-poetry-dep:
  poetry update

@program-all run-python:
  @just update-poetry
  @just update-poetry-lock
  @just update-poetry-dep
  python $1.py
