set positional-arguments := true
alias b := build
alias br := build-release

@build build:
  clang $1.c -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed -o $1

@build-release build:
  clang $1.c -O2 -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed -o $1

@program update-poetry
  poetry self update

@program update-poetry-lock
  poetry lock

@program update-poetry-dep
  poetry update

@program run-python:
  @just update-poetry
  @just update-poetry-lock
  @just update-poetry-dep
  python $1.py
