[package]
name = "load_and_parse_parquets"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["adela-tools"]
description = "Rust CLI to load Parquet files, filter by Elo, parse PGN movetext to SAN moves, and write processed batches"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
regex = "1"
indicatif = "0.17"
parking_lot = "0.12"
num_cpus = "1"
once_cell = "1"
log = "0.4"
env_logger = "0.11"

polars = { version = "0.41", features = [
  "lazy",
  "parquet",
  "strings",
] }
