[project]
name = "zetta"
version = "0.1.0"
description = "Verify diff with LLM"
readme = "README.md"
requires-python = "==3.13.3"
dependencies = [
  "pydantic-ai-slim[logfire,openai]==0.2.9",
  "python-dotenv==1.1.0",
]
