[project]
name = "zetta"
version = "0.1.0"
description = "Breakthrough of SimpleQA"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
  "blake3==1.0.5",
  "httpx==0.28.1",
  "polars==1.30.0",
  "pydantic-ai-slim[logfire,openai]==0.2.19",
  "python-dotenv==1.1.0",
]
