[project]
name = "meteorite"
version = "0.1.0"
description = "Unified school api"
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
  "fastapi[standard]==0.115.9",
  "gel==3.0.1",
  "httpx==0.28.1",
  "loguru==0.7.3",
  "pcfrv==0.2.12",
  "satellite-py==0.1.6",
]

[tool.basedpyright]
reportAny = false
reportUnknownMemberType = false

