[project]
name = "meteorite"
version = "0.1.0"
description = "Unified school api"
readme = "README.md"
requires-python = "==3.13.1"
dependencies = [
  "edgedb==2.2.0",
  "fastapi[standard]==0.115.8",
  "httpx==0.28.1",
  "loguru==0.7.3",
  "pcfrv==0.2.10"
]

[tool.basedpyright]
reportAny = false
reportUnknownMemberType = false

