[project]
name = "meteorite"
version = "0.1.0"
description = "Unified school api"
readme = "README.md"
requires-python = "==3.13.1"
dependencies = [
  "edgedb==2.2.0",
  "fastapi==0.115.6",
  "httpx==0.28.1",
  "pcfrv==0.2.3",
]
