[tool.poetry]
name = "starlighter"
version = "0.1.0"
description = "StarLighting Rhythm Game"
authors = ["MisileLaboratory"]
license = "StarLighter License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.1"
misilelibpy = { path = "libs/misilelib/misilelib-python" }
rich = "13.1.0"
simple-term-menu = "1.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
