[tool.poetry]
name = "starlighter"
version = "0.1.0"
description = "The AI app about light pollution"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"
keras = "2.12.0"
scipy = "1.10.1"
Pillow = "9.5.0"

[tool.poetry.group.scraping.dependencies]
requests = "2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
