# Training Configuration
training:
  output_dir: "./models/checkpoints"
  num_epochs: 100
  batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_ratio: 0.05
  max_grad_norm: 1.0
  fp16: true
  logging_steps: 100
  save_steps: 500
  eval_steps: 500
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "f1"
  greater_is_better: true
  early_stopping_patience: 5
  early_stopping_threshold: 0.001
  dataloader_num_workers: 4
  remove_unused_columns: false

# Data Configuration
data:
  max_length: 512
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  seed: 42
  dataset_name: "jackhhao/jailbreak-classification"
  text_column: "prompt"
  label_column: "type"
  augmentation_enabled: true
  augmentation_prob: 0.3

# Model Configuration
model:
  name: "google/electra-large-discriminator"
  num_labels: 2
  dropout: 0.1
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1

# LoRA Configuration
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["query", "value"]
  bias: "none"
  task_type: "SEQ_CLS"

# Evaluation Configuration
evaluation:
  threshold: 0.5
  metrics: ["accuracy", "precision", "recall", "f1", "roc_auc"]
  save_predictions: true
  save_confusion_matrix: true
  save_roc_curve: true

# Logging Configuration
logging:
  level: "INFO"
  log_dir: "./experiments/logs"
  tensorboard_dir: "./experiments/logs/tensorboard"
  wandb_project: "segment-jailbreak-detection"
  wandb_entity: null

# Hardware Configuration
hardware:
  device: "auto"  # auto, cpu, cuda
  mixed_precision: true
  gradient_checkpointing: false