# Model Hyperparameters
model:
  # Base model configuration
  base_model: "google/electra-large-discriminator"
  num_labels: 2
  problem_type: "single_label_classification"
  
  # Dropout configuration
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  classifier_dropout: 0.1
  
  # Tokenizer configuration
  tokenizer_name: "google/electra-large-discriminator"
  max_length: 512
  truncation: true
  padding: "max_length"
  return_tensors: "pt"
  
  # Model saving configuration
  save_format: "safetensors"
  save_pretrained: true
  
# Training hyperparameters
training:
  # Optimizer settings
  optimizer: "adamw"
  learning_rate: 2e-5
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-8
  max_grad_norm: 1.0
  
  # Scheduler settings
  lr_scheduler_type: "linear"
  warmup_ratio: 0.05
  warmup_steps: 0
  
  # Batch settings
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 4
  
  # Epoch settings
  num_train_epochs: 100
  max_steps: -1
  
  # Evaluation settings
  evaluation_strategy: "steps"
  eval_steps: 500
  eval_delay: 0
  
  # Saving settings
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "f1"
  greater_is_better: true
  
  # Early stopping
  early_stopping_patience: 5
  early_stopping_threshold: 0.001
  
  # Performance settings
  fp16: true
  fp16_opt_level: "O1"
  dataloader_num_workers: 4
  remove_unused_columns: false
  label_names: ["labels"]
  
# LoRA specific configuration
lora:
  enabled: false
  task_type: "SEQ_CLS"
  inference_mode: false
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["query", "value"]
  bias: "none"
  modules_to_save: ["classifier"]
  
# Data augmentation configuration
augmentation:
  enabled: true
  probability: 0.3
  methods:
    - "character_substitution"
    - "case_mixing"
    - "token_stuffing"
  
  # Character substitution settings
  char_sub_prob: 0.1
  char_substitutions:
    "l": "1"
    "o": "0"
    "e": "3"
    "a": "@"
    "s": "$"
    "i": "!"
  
  # Token stuffing settings
  token_stuffing_count: 5
  token_stuffing_tokens: ["<pad>", "<unk>", ".", ",", "!", "?"]
  
  # Case mixing settings
  case_mixing_prob: 0.3