[tool.poetry]
name = "iusearchbtw-backend"
version = "0.1.0"
description = ""
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
pymongo = "4.5.0"
fastapi = "0.103.1"
uvicorn = "0.23.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
