name = "Mekanically-Above"
author = "MisileLaboratory"
version = "0.0.1-rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caa751fc029b6a9229b5dd467bdb4d0927b38db5a49df6440e8a6540ac18d315"

[versions]
forge = "43.2.12"
minecraft = "1.19.2"
