# AUTOGENERATED FROM 'queries/money/set_money.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class SetMoneyResult:
    id: uuid.UUID


async def set_money(
    executor: gel.AsyncIOExecutor,
    *,
    money: int,
    userid: int,
) -> SetMoneyResult | None:
    return await executor.query_single(
        """\
        update User filter .userid = <int64>$userid set {
          money := <int64>$money
        }\
        """,
        money=money,
        userid=userid,
    )
