[project]
name = "schale"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
  {name = "MisileLaboratory", email = "misileminecord@gmail.com"},
]
dependencies = [
  "edgedb==2.0.0",
  "fastapi==0.111.0",
  "uvicorn==0.30.1",
  "pyjwt==2.8.0",
]
requires-python = "==3.12.3"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "ruff-lsp==0.0.54",
  "python-lsp-server==1.11.0",
]
