[project]
name = "schale"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
  {name = "MisileLaboratory", email = "misileminecord@gmail.com"},
]
dependencies = [
  "edgedb==1.9.0",
  "fastapi==0.110.3",
  "slowapi==0.1.9",
  "uvicorn==0.29.0",
  "pyjwt==2.8.0",
]
requires-python = "==3.12.3"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "ruff==0.4.2",
]
