[project]
name = "schale"
version = "0.1.0"
description = "Auth daemon"
authors = [
  {name = "MisileLaboratory", email = "misileminecord@gmail.com"},
]
dependencies = [
  "edgedb==2.0.1",
  "fastapi==0.112.2",
  "uvicorn==0.30.6",
  "pyjwt==2.9.0",
]
requires-python = "==3.12.5"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "ruff-lsp==0.0.55",
  "python-lsp-server==1.12.0",
]
