[tool.poetry]
name = "hvc"
version = "0.1.0"
description = "Hacker's Vulnerability Cracker"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
typing-extensions = "4.7.0"
pyfiglet = "1.0.2"
tqdm = "4.65.1"
requests = "2.31.0"
typer = {extras=["all"], version="0.9.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
