[tool.poetry]
name = "trpgtools"
version = "0.1.0"
description = ""
authors = ["MisileLab"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.3"
gradio = "3.36.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
