[tool.poetry]
name = "trpgtools"
version = "0.1.0"
description = ""
authors = ["MisileLab"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.0"
gradio = "4.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
