# AUTOGENERATED FROM 'queries/user/deposit_to_bank.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class DepositToBankResult:
    id: uuid.UUID


async def deposit_to_bank(
    executor: gel.AsyncIOExecutor,
    *,
    receiver: uuid.UUID,
    senderid: int,
    amount: int,
) -> list[DepositToBankResult]:
    return await executor.query(
        """\
        with
          receiver := (select Bank filter .id = <uuid>$receiver),
          sender := (select User {banks} filter .userid = <int64>$senderid),
          banks := (select sender.banks {id, receiver, amount} filter .receiver = <uuid>$receiver),
          data := (insert Data {amount := <int64>$amount, sender := sender.id, receiver := receiver.id}),
          bank := (
            (update User filter .userid = <int64>$senderid set {banks += (insert Data {
              amount := <int64>$amount,
              sender := sender.id,
              receiver := <uuid>$receiver
            })}).banks if not exists banks else (update banks set {
              amount := .amount + <int64>$amount
            })
          ),
          def := (update sender set {transactions += data, money := .money - <int64>$amount}),
          def2 := (update receiver set {transactions += data, money := .money + <int64>$amount})
        select {def, def2};\
        """,
        receiver=receiver,
        senderid=senderid,
        amount=amount,
    )
