# AUTOGENERATED FROM 'queries/user/extract_from_bank.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class ExtractFromBankResult:
    id: uuid.UUID


async def extract_from_bank(
    executor: gel.AsyncIOExecutor,
    *,
    receiver: uuid.UUID,
    senderid: int,
    amount: int,
) -> list[ExtractFromBankResult]:
    return await executor.query(
        """\
        with
          receiver := (select Bank filter .id = <uuid>$receiver),
          sender := (select User {banks} filter .userid = <int64>$senderid),
          banks := (select sender.banks {id, receiver, amount} filter .receiver = <uuid>$receiver),
          data := (insert Data {amount := <int64>$amount, sender := sender.id, receiver := receiver.id}),
          bank := (update banks set {amount := .amount - <int64>$amount}),
          def := (update sender set {transactions += data, money := .money + <int64>$amount}),
          def2 := (update receiver set {transactions += data, money := .money - <int64>$amount})
        select {def, def2};\
        """,
        receiver=receiver,
        senderid=senderid,
        amount=amount,
    )
