# AUTOGENERATED FROM 'queries/user/get_user_by_uuid.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetUserByUuidResult:
    id: uuid.UUID
    credit: int
    userid: int


async def get_user_by_uuid(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetUserByUuidResult | None:
    return await executor.query_single(
        """\
        select User {credit, userid} filter .id = <uuid>$id;\
        """,
        id=id,
    )
