# AUTOGENERATED FROM 'queries/user/is_any_bank_owner.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import gel


async def is_any_bank_owner(
    executor: gel.AsyncIOExecutor,
    *,
    userid: int,
) -> bool:
    return await executor.query_single(
        """\
        select exists (select Bank filter .owner.userid = <int64>$userid)\
        """,
        userid=userid,
    )
