[project]
name = "flying-cat"
version = "0.1.0"
description = "Detect suicidal from conversation with LLM."
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
  "loguru==0.7.3",
  "polars==1.26.0",
  "pyarrow==19.0.1",
  "pydantic==2.11.1",
  "scikit-learn==1.6.1",
  "soynlp",
  "tiktoken==0.9.0",
  "torch==2.6.0",
  "tqdm==4.67.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu" },
]
soynlp = { git = "https://github.com/MisileLab/soynlp" }

[[tool.uv.index]]
name = "pytorch-cu"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

