[tool.poetry]
name = "mkcl"
version = "0.1.0"
description = "Misile's Key Chord detection Library"
authors = ["MisileLaboratory"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
