[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Backend"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"
#package-mode = false

[tool.poetry.dependencies]
python = "3.12.3"
strawberry-graphql = {extras = ["fastapi"], version = "0.226.0"}
edgedb = "1.9.0"
fastapi = "0.110.1"
python-lsp-server = "1.11.0"
uvicorn = "0.29.0"
python-multipart = "0.0.9"
jwt = "1.3.1"
tomli = "2.0.1"
slowapi = "0.1.9"

[tool.poetry.group.lsp.dependencies]
python-lsp-server = "1.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
