# AUTOGENERATED FROM 'queries/products/add_product.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class AddProductResult:
    id: uuid.UUID


async def add_product(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
    interest: int,
    min_trust: int,
    end_date: int,
    bank_name: str,
) -> AddProductResult | None:
    return await executor.query_single(
        """\
        update Bank filter .name = <str>$bank_name set {
          products += (insert Product {
            name := <str>$name,
            interest := <int64>$interest,
            min_trust := <int64>$min_trust,
            end_date := <int64>$end_date
          })
        }\
        """,
        name=name,
        interest=interest,
        min_trust=min_trust,
        end_date=end_date,
        bank_name=bank_name,
    )
