# AUTOGENERATED FROM 'queries/bank/products/delete_product.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteProductResult(NoPydanticValidation):
    id: uuid.UUID


async def delete_product(
    executor: edgedb.AsyncIOExecutor,
    *,
    bank_name: str,
    name: str,
) -> DeleteProductResult | None:
    return await executor.query_single(
        """\
        delete (select Bank {products: {name}} filter .name = <str>$bank_name and .products.name = <str>$name)\
        """,
        bank_name=bank_name,
        name=name,
    )
