model:
  name: "google/electra-large-discriminator"
  max_length: 256
  num_labels: 2
  dropout: 0.1

training:
  batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 3e-5
  num_epochs: 5
  weight_decay: 0.01
  warmup_ratio: 0.03
  fp16: true
  dataloader_num_workers: 4
  save_strategy: "epoch"
  evaluation_strategy: "epoch"
  load_best_model_at_end: true
  metric_for_best_model: "f1"
  greater_is_better: true
  early_stopping_patience: 3

lora:
  r: 16
  lora_alpha: 32
  target_modules: ["query", "value"]
  lora_dropout: 0.1
  bias: "none"
  task_type: "SEQ_CLS"

data:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  seed: 42
  column_mapping:
    text: "text"
    label: "label"

safety:
  block_threshold: 0.7
  review_threshold: 0.4
  default_threshold: 0.5

logging:
  project_name: "electra-jailbreak-guard"
  log_level: "INFO"
  use_wandb: true
  use_tensorboard: true