[project]
name = "djangosite"
version = "0.1.0"
description = ""
requires-python = "==3.13.1"
dependencies = [
  "channels==4.2.0",
  "django-extensions==3.2.3",
  "django==5.1.4",
  "requests==2.32.3",
]
