[project]
name = "djangosite"
version = "0.1.0"
description = ""
requires-python = "==3.13.1"
dependencies = [
  "argon2-cffi==23.1.0",
  "channels==4.2.0",
  "daphne==4.1.2",
  "django-extensions==3.2.3",
  "django==5.1.6",
  "requests==2.32.3",
]
