# AUTOGENERATED FROM 'queries/products/get_product.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetProductResult:
    id: uuid.UUID
    interest: int
    end_date: int
    max_amount: int
    min_trust: int


async def get_product(
    executor: gel.AsyncIOExecutor,
    *,
    bank_name: str,
    name: str,
) -> GetProductResult | None:
    return await executor.query_single(
        """\
        with
          products := (select Bank {products: {interest, end_date, max_amount, min_trust}} filter .name = <str>$bank_name).products
        select products {interest, end_date, max_amount, min_trust} filter .name = <str>$name;\
        """,
        bank_name=bank_name,
        name=name,
    )
