[tool.poetry]
name = "xms"
version = "0.1.0"
description = "eXpandable Minecraft Server"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
pymongo = "4.5.0"
fastapi = "0.103.2"
websockets = "11.0.3"
uvicorn = "0.23.2"
python-dotenv = "1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
