[tool.poetry]
name = "xms"
version = "0.1.0"
description = "eXpandable Minecraft Server"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.0"
pymongo = "4.6.0"
fastapi = "0.104.1"
websockets = "12.0"
uvicorn = "0.24.0.post1"
python-dotenv = "1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
