[package]
name = "quantumdb-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Command-line interface for QuantumDB"

[[bin]]
name = "quantumdb"
path = "src/main.rs"

[dependencies]
# Core library
quantumdb-core = { path = "../quantumdb-core" }

# CLI
clap = { workspace = true }

# Async runtime
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Progress bars
indicatif = "0.18"

# File system
dirs = "6.0"