# AUTOGENERATED FROM 'queries/user/get_user.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class GetUserResult:
    id: uuid.UUID
    credit: int
    userid: int


async def get_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetUserResult | None:
    return await executor.query_single(
        """\
        select User {credit, userid} filter .id = <uuid>$id;\
        """,
        id=id,
    )
