# AUTOGENERATED FROM 'queries/user/get_user_banks.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserBanksResult(NoPydanticValidation):
    id: uuid.UUID
    banks: list[GetUserBanksResultBanksItem]
    money: int


@dataclasses.dataclass
class GetUserBanksResultBanksItem(NoPydanticValidation):
    id: uuid.UUID
    amount: int
    sender: uuid.UUID


async def get_user_banks(
    executor: edgedb.AsyncIOExecutor,
    *,
    userid: int,
) -> GetUserBanksResult | None:
    return await executor.query_single(
        """\
        select (select User { banks: {amount, sender}, money } filter .userid = <int64>$userid);\
        """,
        userid=userid,
    )
