# AUTOGENERATED FROM 'queries/user/get_user_banks.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class GetUserBanksResult:
    id: uuid.UUID
    banks: list[GetUserBanksResultBanksItem]
    money: int
    credit: int


@dataclasses.dataclass
class GetUserBanksResultBanksItem:
    id: uuid.UUID
    amount: int
    receiver: uuid.UUID


async def get_user_banks(
    executor: edgedb.AsyncIOExecutor,
    *,
    userid: int,
) -> GetUserBanksResult | None:
    return await executor.query_single(
        """\
        insert User {
          credit := 0,
          userid := <int64>$userid
        } unless conflict on .userid;
        select (select User { banks: {amount, receiver}, money, credit } filter .userid = <int64>$userid);\
        """,
        userid=userid,
    )
