# AUTOGENERATED FROM 'queries/user/get_user_banks.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class GetUserBanksResult:
    id: uuid.UUID
    banks: list[GetUserBanksResultBanksItem]
    money: int


@dataclasses.dataclass
class GetUserBanksResultBanksItem:
    id: uuid.UUID
    amount: int
    sender: uuid.UUID


async def get_user_banks(
    executor: edgedb.AsyncIOExecutor,
    *,
    userid: int,
) -> GetUserBanksResult | None:
    return await executor.query_single(
        """\
        select (select User { banks: {amount, sender}, money } filter .userid = <int64>$userid);\
        """,
        userid=userid,
    )
