# AUTOGENERATED FROM 'queries/user/is_any_bank_owner.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import edgedb


async def is_any_bank_owner(
    executor: edgedb.AsyncIOExecutor,
    *,
    userid: int,
) -> bool:
    return await executor.query_single(
        """\
        select exists (select Bank filter .owner.userid = <int64>$userid)\
        """,
        userid=userid,
    )
