# AUTOGENERATED FROM 'queries/user/send.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class SendResult:
    id: uuid.UUID


async def send(
    executor: edgedb.AsyncIOExecutor,
    *,
    receiverid: int,
    senderid: int,
    amount: int,
    sender_money: int,
    receiver_money: int,
) -> SendResult | None:
    return await executor.query_single(
        """\
        with
          receiver := (select User filter .userid = <int64>$receiverid),
          sender := (select User filter .userid = <int64>$senderid),
          data := (insert Data {amount := <int64>$amount, sender := sender.id, receiver := receiver.id}),
          def := (update sender set {transactions += data, money := <int64>$sender_money})
        update receiver set {transactions += data, money := <int64>$receiver_money};\
        """,
        receiverid=receiverid,
        senderid=senderid,
        amount=amount,
        sender_money=sender_money,
        receiver_money=receiver_money,
    )
