[tool.poetry]
name = "sntapi"
version = "0.1.0"
description = ""
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"
fastapi = "0.107.0"
uvicorn = "0.25.0"
pymongo = "4.6.1"
python-dotenv = "1.0.0"
selenium = "4.16.0"
pydantic = "2.5.3"
pypdf = "^3.17.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
