"""
This type stub file was generated by pyright.
"""

from .interactive import get_user_credentials

"""oauthlib integration for Google Auth

This library provides `oauthlib <https://oauthlib.readthedocs.io/>`__
integration with `google-auth <https://google-auth.readthedocs.io/>`__.
"""
__all__ = ["get_user_credentials"]
