[package]
name = "quantumdb-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Python bindings for QuantumDB"

[lib]
name = "quantumdb"
crate-type = ["cdylib"]

[dependencies]
# Core library
quantumdb-core = { path = "../quantumdb-core" }

# Python bindings
pyo3 = { version = "0.26", features = ["extension-module"] }
numpy = { version = "0.26" }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }