[tool.poetry]
name = "sunrint-decon"
version = "0.1.0"
description = ""
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.0"
pymongo = "4.6.0"
fastapi = "0.104.1"
uvicorn = "0.24.0"
tomli = "2.0.1"
requests = "2.31.0"
strawberry-graphql = {extras = ["debug-server"], version = "^0.211.1"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
