[project]
name = "cocktail"
version = "0.1.0"
description = "Blend all, send anonymously"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "fastapi==0.111.0",
  "websockets==12.0",
  "uvicorn==0.30.1",
  "orjson==3.10.4",
  "pycryptodome==3.20.0",
]
requires-python = "==3.12.3"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "ruff==0.4.8",
]
