[project]
name = "reactor"
version = "0.1.0"
description = "Reactor monitoring and control system"
readme = "README.md"
requires-python = "==3.13.5"
dependencies = [
  "gel==3.1.0",
  "websockets==15.0.1",
]
