[tool.poetry]
name = "starlighter"
version = "0.1.0"
description = "The AI app about light pollution"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"
keras = "2.13.1"
scipy = "1.11.1"
Pillow = "10.0.0"

[tool.poetry.group.scraping.dependencies]
requests = "2.31.0"
python-dotenv = "1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
