[tool.poetry]
name = "jupyters"
version = "0.1.0"
description = "Julia, Python, Not using r"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"
numpy = "1.25.1"
jupyterlab = "4.0.3"
ipykernel = "6.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
