[project]
name = "cocktail"
version = "0.1.0"
description = "Blend all, send anonymously"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "fastapi==0.115.2",
  "websockets==13.1",
  "uvicorn==0.32.0",
  "orjson==3.10.9",
  "pycryptodome==3.21.0",
]
requires-python = "==3.12.5"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "ruff==0.7.0",
]
