[project]
name = "cocktail"
version = "0.1.0"
description = "Blend all, send anonymously"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "fastapi==0.115.4",
  "websockets==13.1",
  "uvicorn==0.32.0",
  "orjson==3.10.11",
  "pycryptodome==3.21.0",
]
requires-python = "==3.13.0"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

