If Parsley does not exist {
    ...@b.d2
    Users.doc <- Users.vote: Vote to submitted doc, not anon
    Users.doc -> Administrators.doc: If it has many votes
    Administrators.doc <- Administrators.vote: This is private, and We can get only result
}

If parsley exist {
    ...@b.d2
    parsley
    Users.doc -> parsley: Submit the doc anon
    Users.vote -> Users.doc: Vote the doc anon
    parsley -> Administrators.doc: Admin get only number and doc
    Administrators.vote -> Administrators.doc: They talk about that with user publicly and vote
    Administrators.doc -> parsley: Go to db, user can view
}
