[package]
name = "quantumdb-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "gRPC/HTTP server for QuantumDB"

[dependencies]
# Core library
quantumdb-core = { path = "../quantumdb-core" }

# Async and networking
tokio = { workspace = true }
tonic = { workspace = true, optional = true }
prost = { workspace = true, optional = true }
axum = { version = "0.8", optional = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# HTTP (optional)
hyper = { version = "1.0", optional = true }
tower = { version = "0.5", optional = true }

[build-dependencies]
tonic-build = "0.14"

[features]
default = ["grpc", "http"]
grpc = ["dep:tonic", "dep:prost"]
http = ["dep:axum", "dep:hyper", "dep:tower"]