[project]
name = "myhandnomusa"
version = "0.1.0"
description = ""
requires-python = ">=3.13.6"
dependencies = [
  "fastapi[standard]>=0.116.1",
  "openai>=1.106.1",
  "polars>=1.33.0",
  "pyarrow>=21.0.0",
]
