[project]
name = "myhandnomusa"
version = "0.1.0"
description = ""
requires-python = "==3.13.6"
dependencies = [
  "fastapi[standard]==0.116.1",
  "httpx==0.28.1",
  "openai==1.107.0",
  "polars==1.33.1",
  "pyarrow==21.0.0",
  "python-dotenv==1.1.1",
  "tqdm==4.67.1",
]
