[package]
name = "quantumdb-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Core library for QuantumDB neural compression and vector search"

[dependencies]
# ML framework
burn = { workspace = true }
safetensors = { workspace = true }

# Data structures
dashmap = { workspace = true }
crossbeam = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }

# SIMD
portable-simd = { workspace = true }

# Memory and storage
memmap2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Math
ndarray = { workspace = true }
num-traits = { workspace = true }
ordered-float = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }

# Data processing
arrow = { workspace = true }
parquet = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "training"
harness = false

[[bench]]
name = "inference" 
harness = false

[[bench]]
name = "search"
harness = false