[project]
name = "esgithub"
version = "0.1.0"
description = "Search your issues and pull requests with embedding."
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
  "embed-anything==0.5.3",
  "pygithub==2.6.1",
  "tqdm==4.67.1",
  "typer==0.15.2",
]
