name = "Mekanically: Dynamic"
author = "MisileLaboratory"
version = "1.22.0.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0d767e2abdf37237989e995aa15df00b3936099ca8b191719dc5f686811f1c6"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
