# AUTOGENERATED FROM 'queries/bank/get_bank_products.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetBankProductsResult:
    id: uuid.UUID
    products: list[GetBankProductsResultProductsItem]


@dataclasses.dataclass
class GetBankProductsResultProductsItem:
    id: uuid.UUID
    name: str
    min_trust: int
    interest: int
    end_date: int
    max_amount: int


async def get_bank_products(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
) -> GetBankProductsResult | None:
    return await executor.query_single(
        """\
        select default::Bank {
          products: {name, min_trust, interest, end_date, max_amount}
        }
        filter .name = <str>$name\
        """,
        name=name,
    )
