# AUTOGENERATED FROM 'queries/bank/get_bank_money.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetBankMoneyResult:
    id: uuid.UUID
    money: int


async def get_bank_money(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
) -> GetBankMoneyResult | None:
    return await executor.query_single(
        """\
        select Bank {money} filter .name = <str>$name;\
        """,
        name=name,
    )
