[project]
name = "soup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.1.1",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "safetensors>=0.6.2",
    "tiktoken>=0.11.0",
    "torch>=2.8.0",
    "torchtext>=0.6.0",
]
