[package]
name = "train_adela"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
polars = { version = "0.50.0", features = ["parquet", "lazy", "dtype-categorical"] }
shakmaty = { version = "0.29.1" }
thiserror = "2.0.12"
rayon = "1.10"

ndarray = "0.16.1"
tch = { version = "0.20.0", features = ["download-libtorch"] }
indicatif = "0.18.0"
walkdir = "2.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
