# AUTOGENERATED FROM 'queries/add_school.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class AddSchoolResult:
    id: uuid.UUID


async def add_school(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
    school_code: int,
    ofcdc_code: str,
) -> AddSchoolResult:
    return await executor.query_single(
        """\
        insert Lunch::School {
          name := <str>$name,
          school_code := <int64>$school_code,
          ofcdc_code := <str>$ofcdc_code
        }\
        """,
        name=name,
        school_code=school_code,
        ofcdc_code=ofcdc_code,
    )
