[project]
name = "kali"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.5"
dependencies = [
  "inquirer==3.4.0",
  "pydantic-ai-slim[logfire,openai]==0.4.10",
  "python-dotenv==1.1.1",
]
