[project]
name = "simplemoney"
version = "0.1.0"
description = "simple discord bot for private minecraft"
readme = "README.md"
requires-python = "==3.13.1"
dependencies = [
  "disnake==2.10.1",
  "tomli==2.2.1",
]
