[project]
name = "simplemoney"
version = "0.1.0"
description = "simple money system"
authors = [
  {name = "misile", email = "misile@duck.com"},
]
dependencies = [
  "fastapi[standard]==0.115.3",
  "websockets==13.1",
  "edgedb==2.1.0",
  "loguru==0.7.2"
]
# https://github.com/edgedb/edgedb-python/issues/525
# https://github.com/MagicStack/httptools/issues/104
requires-python = ">=3.12.5,<3.13"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false
