[project]
name = "simplemoney"
version = "0.1.0"
description = "simple discord bot for private minecraft"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
  "disnake==2.10.1",
  "gel==3.1.0",
  "pydantic==2.11.6",
  "tomli==2.2.1",
  "tomli-w==1.2.0",
]
