[project]
name = "simplemoney"
version = "0.1.0"
description = "A simple money system for Minecraft"
# https://github.com/edgedb/edgedb-python/issues/525
requires-python = "==3.12.6"
dependencies = [
  "altcha==0.1.4",
  "edgedb==2.1.0",
  "fastapi[standard]==0.115.4",
  "tomli==2.0.2"
]
