[project]
name = "simplemoney"
version = "0.1.0"
description = "A simple money system for Minecraft"
requires-python = "==3.13.1"
dependencies = [
  "argon2-cffi==23.1.0",
  "edgedb==2.2.0",
  "fastapi[standard]==0.115.6",
  "loguru==0.7.3",
  "websockets==14.1",
]
