# AUTOGENERATED FROM 'queries/loan/add_loan.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


@dataclasses.dataclass
class AddLoanResult:
    id: uuid.UUID


async def add_loan(
    executor: edgedb.AsyncIOExecutor,
    *,
    receiver_id: int,
    bank_name: str,
    product_id: uuid.UUID,
    amount: int,
    date: datetime.datetime,
    bank_money: int,
    receiver_money: int,
) -> AddLoanResult | None:
    return await executor.query_single(
        """\
        with
          receiver := (select User filter .userid = <int64>$receiver_id),
          sender := (select Bank filter .name = <str>$bank_name),
          product := (select Product filter .id = <uuid>$product_id),
          exist_loan := (select Loan filter .receiver = receiver.id and .sender = sender.id and .product = product),
          inserted_loan := (insert Loan {
              amount := <int64>$amount,
              receiver := receiver.id,
              sender := sender.id,
              product := product,
              date := <datetime>$date
          }),
          loan := exist_loan ?? inserted_loan
        update Bank set {
          loans += loan,
          money := <int64>$bank_money
        };
        update User filter .userid = <int64>$receiver_id set {money := <int64>$receiver_money};\
        """,
        receiver_id=receiver_id,
        bank_name=bank_name,
        product_id=product_id,
        amount=amount,
        date=date,
        bank_money=bank_money,
        receiver_money=receiver_money,
    )
