# AUTOGENERATED FROM 'queries/loan/get_loan_bank.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


@dataclasses.dataclass
class GetLoanBankResult:
    id: uuid.UUID
    date: datetime.datetime
    amount: int
    receiver: uuid.UUID
    product: GetLoanBankResultProduct


@dataclasses.dataclass
class GetLoanBankResultProduct:
    id: uuid.UUID
    interest: int
    name: str


async def get_loan_bank(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
) -> list[GetLoanBankResult]:
    return await executor.query(
        """\
        select (select Bank {loans: {date, amount, receiver, product: {interest, name}}} filter .name = <str>$name).loans;\
        """,
        name=name,
    )
