# AUTOGENERATED FROM 'queries/loan/get_loan_amount.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class GetLoanAmountResult:
    id: uuid.UUID
    amount: int


async def get_loan_amount(
    executor: edgedb.AsyncIOExecutor,
    *,
    userid: int,
    sender: uuid.UUID,
    product_name: str,
) -> GetLoanAmountResult | None:
    return await executor.query_single(
        """\
        with
          user := (select User {id} filter .userid = <int64>$userid)
        select Loan {amount}
        filter .receiver = user.id and .sender = <uuid>$sender and .product.name = <str>$product_name
        limit 1;\
        """,
        userid=userid,
        sender=sender,
        product_name=product_name,
    )
