# AUTOGENERATED FROM 'queries/loan/get_loan_expired.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetLoanExpiredResult:
    id: uuid.UUID
    receiver: uuid.UUID
    date: datetime.datetime
    product: GetLoanExpiredResultProduct
    amount: int


@dataclasses.dataclass
class GetLoanExpiredResultProduct:
    id: uuid.UUID
    end_date: int
    interest: int


async def get_loan_expired(
    executor: gel.AsyncIOExecutor,
) -> list[GetLoanExpiredResult]:
    return await executor.query(
        """\
        select Loan {id, receiver, date, product: {end_date, interest}, amount} filter .date < datetime_current();\
        """,
    )
