# AUTOGENERATED FROM 'queries/loan/get_loan_user.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetLoanUserResult:
    id: uuid.UUID
    receiver: uuid.UUID
    date: datetime.datetime
    product: GetLoanUserResultProduct
    amount: int


@dataclasses.dataclass
class GetLoanUserResultProduct:
    id: uuid.UUID
    end_date: int
    interest: int
    name: str


async def get_loan_user(
    executor: gel.AsyncIOExecutor,
    *,
    userid: int,
) -> list[GetLoanUserResult]:
    return await executor.query(
        """\
        with
          user := (select User {id} filter .userid = <int64>$userid)
        select Loan {id, receiver, date, product: {end_date, interest, name}, amount} filter .receiver = user.id;\
        """,
        userid=userid,
    )
