# AUTOGENERATED FROM 'queries/loan/pay_loan.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class PayLoanResult:
    id: uuid.UUID


async def pay_loan(
    executor: edgedb.AsyncIOExecutor,
    *,
    receiver_id: int,
    bank_name: str,
    product_name: str,
    amount: int,
    bank_money: int,
    receiver_money: int,
) -> list[PayLoanResult]:
    return await executor.query(
        """\
        with
          receiver := (select User filter .userid = <int64>$receiver_id),
          sender := (select Bank filter .name = <str>$bank_name),
          loan := (select Loan filter .sender = sender.id and .receiver = receiver.id and .product.name = <str>$product_name),
        update loan set {amount := .amount - <int64>$amount};
        update Bank set {money := <int64>$bank_money};
        update User filter .userid = <int64>$receiver_id set {money := <int64>$receiver_money};
        delete Loan filter .amount = 0;\
        """,
        receiver_id=receiver_id,
        bank_name=bank_name,
        product_name=product_name,
        amount=amount,
        bank_money=bank_money,
        receiver_money=receiver_money,
    )
