# AUTOGENERATED FROM 'queries/loan/refresh_loan.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class RefreshLoanResult:
    id: uuid.UUID


async def refresh_loan(
    executor: gel.AsyncIOExecutor,
    *,
    date: datetime.datetime,
    amount: int,
    id: uuid.UUID,
    credit: int,
    userid: uuid.UUID,
) -> RefreshLoanResult | None:
    return await executor.query_single(
        """\
        update Loan filter .id = <uuid>$id set {
          date := <datetime>$date,
          amount := <int64>$amount
        };
        update User filter .id = <uuid>$userid set {
          credit := <int64>$credit
        };\
        """,
        date=date,
        amount=amount,
        id=id,
        credit=credit,
        userid=userid,
    )
