# AUTOGENERATED FROM 'queries/loan/reset_loan.edgeql' WITH:
#     $ edgedb-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class ResetLoanResult:
    id: uuid.UUID


async def reset_loan(
    executor: edgedb.AsyncIOExecutor,
    *,
    userid: int,
) -> list[ResetLoanResult]:
    return await executor.query(
        """\
        delete Loan filter .receiver = (select User filter .userid = <int64>$userid).id;\
        """,
        userid=userid,
    )
