[tool.poetry]
name = "lambda"
version = "0.1.0"
description = "Lambda Backend"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
