[project]
name = "schale"
version = "0.1.0"
description = "Backend of schale"
requires-python = "==3.13.1"
dependencies = [
  "boto3==1.36.5",
  "fastapi[standard]==0.115.7",
  "tomli==2.2.1",
  "python-multipart==0.0.20",
  "argon2-cffi==23.1.0",
  "blake3==1.0.4",
  "satellite-py==0.1.1",
]

[tool.basedpyright]
reportAny = false
reportUnknownMemberType = false

