[project]
name = "schale"
version = "0.1.0"
description = "Backend of schale"
requires-python = "==3.13.1"
dependencies = [
  "boto3==1.35.80",
  "edgedb==2.2.0",
  "fastapi[standard]==0.115.6",
  "tomli==2.2.1",
  "python-multipart==0.0.19",
  "argon2-cffi==23.1.0",
  "blake3==1.0.0",
]
