[tool.poetry]
name = "slhc"
version = "0.1.0"
description = "Surfing Linux, Hacking Computer"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.3"
typer = {extras = ["all"], version = "0.7.0"}
typer-builder = "0.0.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
