# AUTOGENERATED FROM 'queries/user/get_user.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetUserResult:
    id: uuid.UUID
    credit: int
    userid: int


async def get_user(
    executor: gel.AsyncIOExecutor,
    *,
    userid: int,
    id: uuid.UUID,
) -> GetUserResult | None:
    return await executor.query_single(
        """\
        insert User {
          credit := 0,
          userid := <int64>$userid
        } unless conflict on .userid;
        select User {credit, userid} filter .id = <uuid>$id;\
        """,
        userid=userid,
        id=id,
    )
