# AUTOGENERATED FROM 'queries/user/send.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class SendResult:
    id: uuid.UUID


async def send(
    executor: gel.AsyncIOExecutor,
    *,
    receiverid: int,
    senderid: int,
    amount: int,
    fee: float,
) -> list[SendResult]:
    return await executor.query(
        """\
        with
          receiver := (select User filter .userid = <int64>$receiverid),
          sender := (select User filter .userid = <int64>$senderid),
          data := (insert Data {amount := <int64>$amount, sender := sender.id, receiver := receiver.id}),
          def := (update sender set {transactions += data, money := .money - <int64>$amount}),
          def2 := (update receiver set {
            transactions += data,
            money := .money + <int64>$amount - <int64>(math::ceil(<int64>$amount / 100 * <float64>$fee))
          })
        select {def, def2};\
        """,
        receiverid=receiverid,
        senderid=senderid,
        amount=amount,
        fee=fee,
    )
