[project]
name = "cryptohacks"
version = "0.1.0"
description = "Environment for cryptohacks"
authors = [
  {name = "misilelab", email = "misileminecord@gmail.com"},
]
dependencies = [
  "pycryptodome==3.20.0"
]
requires-python = "==3.12.5"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false
