[project]
name = "spectator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.5"
dependencies = [
  "jupyter>=1.1.1",
  "matplotlib>=3.10.5",
  "numpy>=2.3.2",
  "openai>=1.99.0",
  "polars>=1.32.0",
  "requests>=2.32.4",
  "safetensors>=0.5.3",
  "scikit-learn>=1.7.1",
  "seaborn>=0.13.2",
  "torch>=2.7.1",
  "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
  "mypy>=1.17.1",
  "pytest>=8.4.1",
  "ruff>=0.12.7",
]
