# AUTOGENERATED FROM 'queries/credit/set_credit.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class SetCreditResult:
    id: uuid.UUID


async def set_credit(
    executor: gel.AsyncIOExecutor,
    *,
    userid: int,
    credit: int,
) -> SetCreditResult:
    return await executor.query_single(
        """\
        insert User {
          userid := <int64>$userid,
          credit := <int64>$credit
        } unless conflict on .userid else (
          update User set {
            credit := <int64>$credit
          })\
        """,
        userid=userid,
        credit=credit,
    )
