[tool.poetry]
name = "various"
version = "0.1.0"
description = "Various things"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"
orjson = "3.9.2"
misilelibpy = {path="libs/misilelib/misilelib-python"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
