name = "Mekanically"
author = "Misile, troll1005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfd28379611313eafed10f0cb2c8bb9f0e4ea9c4b817e14f0939c05477e447b1"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
