name = "Mekanically"
author = "Misile, troll1005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e4620472410d88bc94d2fd6fed06700ef4ae64afd225dc3e328b9b819f62489"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
