name = "Mekanically"
author = "Misile, troll1005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e6e2702927e0e7a0d87bdf3736ff4a3bdab6e46b7169b3e3dc17de56aaa19d8"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
