name = "Mekanically"
author = "Misile, troll1005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f935c86d50aba05d774114f1872c31cd35438e6344a87a53dc903126519cc9e8"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
