name = "Mekanically"
author = "Misile, troll1005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f6b42fd25355c23123caf29bba812bb58c0c3ae90bcf660240a10efc28904ff"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
