name = "mekanically"
author = "MisileLab, troll1005"
version = "0.0.1-rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64554604c2dc6f8c7c421a2bd21df83b3c5d1690e2f9f300d9107e67d67eff48"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
