name = "mekanically"
author = "MisileLab, troll1005"
version = "0.0.1-rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c1eb0cd21dd1844b4058c1ebe08cedca9ad4ecac2a6c73e698788ad93afde77"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
