name = "mekanically"
author = "MisileLab, troll1005"
version = "0.0.1-rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "085274bbe3c63ba9c1d8de7f61d215d0820ebf05e545384e1d06ba6b657e870e"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
