name = "Mekanically"
author = "Misile, troll1005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5290f34faa9df2beb3132bbcb747320020844eb6a1a340cf6b349158de0c264b"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
