name = "Mekanically"
author = "Misile, troll1005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93129391eaaa5d89fc1c69c84842aafb27a8894922ea1003655bf05b36641ce3"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
