[project]
name = "dhs"
version = "0.1.0"
description = "dreamhacks"
requires-python = "==3.13.2"
dependencies = [
  "beautifulsoup4==4.13.4",
  "flask==3.1.0",
  "httpx==0.28.1",
  "loguru==0.7.3",
  "lxml==5.3.2",
  "numpy==2.2.5",
  "promise==2.3",
  "selenium==4.31.0"
]

[project.optional-dependencies]
legacy = [
  "pwntools==4.14.1"
]

[tool.uv]
dev-dependencies = [
  "tqdm==4.67.1"
]
