name = "LightMekanically"
author = "MisileLaboratory"
version = "0.0.1-rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d620a2b666982370ae85b5007cfcf356c2cbbdf3a762cb53cc7811ea0e77dea6"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
