name = "LightMekanically"
author = "MisileLaboratory"
version = "0.0.1-rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e5d56cb4af4a2a621a9ac168b3437add19b1fcfa323717f0d7c72d8fbe81c9c"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
