name = "LightMekanically"
author = "MisileLaboratory"
version = "0.0.1-rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1d50b970280d373658a02d713dae5eb954ab5e38bb61039ec612efcfb3f0b70"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
