[project]
name = "problems"
version = "0.1.0"
description = "sub monorepo for problems"
readme = "README.md"
requires-python = "==3.13.1"
dependencies = [
  "beautifulsoup4==4.12.3",
  "flask==3.1.0",
  "httpx==0.28.1",
  "lxml==5.3.0",
  "numpy==2.2.1",
  "pwntools==4.14.0",
  "tqdm==4.67.1",
]
