[project]
name = "vivian"
version = "0.1.0"
description = "Block youtube's bot comment with embedding"
readme = "README.md"
requires-python = ">=3.13.4"
dependencies = [
  "keras==3.10.0",
  "polars==1.31.0",
  "pydantic==2.11.7",
  "python-youtube==0.9.7",
  "voyageai==0.3.2",
  "torch==2.7.1",
  "pytorch-triton-rocm==3.3.1 ; sys_platform == 'linux'",
  "gradio==5.34.2",
  "openai==1.91.0",
  "tqdm==4.67.1",
  "pydantic-ai-slim[openai]==0.3.2",
  "marimo==0.14.6",
  "anthropic==0.54.0",
  "plotly==6.1.2",
  "pyarrow==20.0.0",
  "transformers==4.52.4",
  "sentence-transformers==4.1.0",
  "datasets==3.6.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
pytorch-triton-rocm = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.3"
explicit = true

