[project]
name = "vivian"
version = "0.1.0"
description = "Block youtube's bot comment with embedding"
readme = "README.md"
requires-python = ">=3.13.4"
dependencies = [
  "keras==3.10.0",
  "polars==1.31.0",
  "pydantic==2.11.7",
  "python-youtube==0.9.7",
  "torch==2.7.1",
  "gradio==5.34.2",
  "openai==1.92.2",
  "tqdm==4.67.1",
  "pydantic-ai-slim[openai]==0.3.4",
  "marimo==0.14.8",
  "anthropic==0.55.0",
  "plotly==6.2.0",
  "pyarrow==20.0.0",
  "transformers==4.53.0",
  "datasets==3.6.0",
  "protobuf==6.31.1",
  "altair==5.5.0",
  "python-lsp-server==1.12.2",
  "websockets==15.0.1",
  "python-lsp-ruff==2.2.2",
]

