[project]
name = "lightstream"
version = "0.1.0"
description = "PoW DDos protection"
requires-python = ">=3.13.2"
dependencies = [
  "argon2-cffi==25.1.0",
  "cryptography==45.0.4",
  "fastapi[standard]==0.115.13",
  "httpx==0.28.1",
  "pyjwt==2.10.1",
  "pytest==8.4.1",
]
