name: deploy dist

on:
  push:
    paths:
      - '.github/workflows/dist.yml'
      - 'dist/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: exist
        shell: bash
        run: |
          if [[ -d "dist" ]]; then
            touch not-exist-really
          fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: ${{ hashFiles('not-exist-really') != '' }}
        with:
          branch: gh-pages
          folder: dist
