name: modpack export

on:
  push:
    paths:
      - '.github/workflows/modpacks.yml'
      - 'modpacks/**'

env:
  GIT_SSL_NO_VERIFY: true

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: .github/filters.yml

    # - if: steps.changes.outputs.src == 'true'
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.2'
        check-latest: true
    - run: |
        go install github.com/packwiz/packwiz@latest
    - if: steps.changes.outputs.mekanically == 'true'
      run: |
        cd modpacks/mekanically
        packwiz curseforge export
        cd -
    - if: steps.changes.outputs.lightmekanically == 'true'
      run: |
        cd modpacks/lightmekanically
        packwiz curseforge export
        cd -
    - name: Mekanically
      if: steps.changes.outputs.mekanically == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: mekanically
        path: modpacks/mekanically/*.zip
    - name: Mekanically
      if: steps.changes.outputs.lightmekanically == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: lightmekanically
        path: modpacks/lightmekanically/*.zip
