name: test

on:
  push:
    paths:
      - '.github/workflows/railway.yml'
      - 'modpacks/railway/*'
      - 'modpacks/basemodpack'

jobs:
  build:
    strategy:
      matrix:
        os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20.1'
        check-latest: true
    - run: |
      go install github.com/packwiz/packwiz@latest
      cd modpacks/railway
      packwiz mr export
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: modpacks/railway/*.mrpack
