name: Check codebase using Sourcery

on:
  push:
    paths:
      - '.github/workflows/sourcery.yml'
      - 'projects/**.py'
      - 'projects/**.ts'
      - 'projects/**.js'

jobs:
  review-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: sourcery-ai/action@v1
        with:
          in_place: true
          token: ${{ secrets.SOURCERY_TOKEN }}

      - name: push
        continue-on-error: true
        run: |
          git config --global user.name 'MisileLaboratory'
          git config --global user.email 'MisileLaboratory@users.noreply.github.com'
          git commit -am "sourcery change"
          git push
