name = "Transactions"
author = "misilelab"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63440a08b45b929fd131902665b449d797355a2a7b01908e5d78b6f9a108674c"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
