name = "Transactions"
author = "misilelab"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f43a196799900981617fb7fbdd347d4917d62eb75d94a78918b47d75904d58d"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
